projects:
  stefanotambelliniwebgraphqlapi:
    schemaPath: amplify/backend/api/stefanotambelliniwebgraphqlapi/build/schema.graphql
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: API.ts
        docsFilePath: graphql
extensions:
  amplify:
    version: 3
